

-- ADDRESS TABLE CREATION

CREATE TABLE SC_ADDRESS 
(
  ADDRESS_ID CHAR(36) NOT NULL 
, PHONE VARCHAR2(100) 
, ADDRESS VARCHAR2(100) 
, POSTALCODE VARCHAR2(100) 
, CITY VARCHAR2(100) 
, COUNTRY VARCHAR2(100) 
, STATE VARCHAR2(100) 
, CONSTRAINT SC_ADDRESS_PK PRIMARY KEY 
  (
    ADDRESS_ID 
  )
  ENABLE 
);

-- PRODUCT STORE TABLE CREATION

CREATE TABLE SC_PRODUCT_STORE 
(
  PRODUCT_STORE_ID CHAR(36) NOT NULL 
, PRODUCT_STORE_NAME VARCHAR2(100) 
, ADDRESS_ID CHAR(36) NOT NULL 
, CONSTRAINT SC_PRODUCT_STORE_PK PRIMARY KEY 
  (
    PRODUCT_STORE_ID 
  )
  ENABLE 
);

ALTER TABLE SC_PRODUCT_STORE
ADD CONSTRAINT SC_PRODUCT_STORE_SC_ADDRE_FK1 FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES SC_ADDRESS
(
  ADDRESS_ID 
)
ON DELETE CASCADE ENABLE;
